"""Pilot factory configuration.

One qualified 3-axis VMC and one indexed 3+2 VMC, the tooling and workholding
that go with them, validated cutting rules for three materials, and a FANUC post
per machine. This is the "one pilot factory, exact machine model" that PRD 16.1
requires before engineering kickoff.
"""

from __future__ import annotations

from typing import Any

#: Spindle curves as [rpm, kW, Nm] samples.
MACHINES: list[dict[str, Any]] = [
    {
        "code": "VMC-01",
        "name": "Robodrill cell 1",
        "manufacturer": "FANUC",
        "model": "Robodrill alpha-D21MiB5",
        "controller": "FANUC",
        "controller_version": "31i-B5",
        "kinematics": "3axis",
        "travels_mm": {"X": [-150.0, 150.0], "Y": [-100.0, 100.0], "Z": [-160.0, 40.0]},
        "spindle_curve": [[0, 1.5, 0], [1500, 11.0, 70.0], [10000, 11.0, 10.5], [24000, 5.5, 2.2]],
        "max_rpm": 24000.0,
        "min_rpm": 50.0,
        "max_feed_mm_min": 30000.0,
        "rapid_mm_min": {"X": 50000.0, "Y": 50000.0, "Z": 48000.0},
        "acceleration_mm_s2": {"X": 10000.0, "Y": 10000.0, "Z": 9000.0},
        "tool_change_seconds": 1.6,
        "index_seconds": 0.0,
        "magazine_capacity": 21,
        "coolant": ["flood", "mist", "through"],
        "work_offsets": ["G54", "G55", "G56", "G57", "G58", "G59"],
        "hourly_rate": 58.0,
        "setup_rate": 52.0,
        "geometry_qualified": True,
        "machine_geometry": {
            "table": {"type": "box", "min": [-260, -180, -170], "max": [260, 180, -160]},
            "column_clearance_mm": 120,
            "qualification": "Travel and collision cases verified against manufacturer drawing 2026-03",
        },
    },
    {
        "code": "VMC-02",
        "name": "Trunnion cell 2",
        "manufacturer": "Brother",
        "model": "SPEEDIO M200X3",
        "controller": "FANUC",
        "controller_version": "31i-B5",
        "kinematics": "3+2",
        "rotary_axes": {"B": {"range_deg": [-120.0, 120.0], "increment_deg": 0.001}, "C": {"range_deg": [0.0, 360.0]}},
        "travels_mm": {"X": [-250.0, 250.0], "Y": [-200.0, 200.0], "Z": [-200.0, 50.0]},
        "spindle_curve": [[0, 2.0, 0], [2000, 16.0, 76.0], [12000, 16.0, 12.7], [16000, 10.0, 6.0]],
        "max_rpm": 16000.0,
        "min_rpm": 50.0,
        "max_feed_mm_min": 30000.0,
        "rapid_mm_min": {"X": 50000.0, "Y": 50000.0, "Z": 50000.0},
        "acceleration_mm_s2": {"X": 12000.0, "Y": 12000.0, "Z": 11000.0},
        "tool_change_seconds": 1.4,
        "index_seconds": 2.2,
        "magazine_capacity": 22,
        "coolant": ["flood", "through"],
        "work_offsets": ["G54", "G55", "G56", "G57"],
        "hourly_rate": 74.0,
        "setup_rate": 58.0,
        "geometry_qualified": True,
        "machine_geometry": {
            "trunnion": {"type": "cylinder", "center": [0, 0, -160], "radius": 160, "z_min": -200, "z_max": -150},
            "qualification": "Trunnion sweep and B-axis clearance verified 2026-04",
        },
    },
    {
        "code": "VMC-03",
        "name": "Bench mill (small travel)",
        "manufacturer": "Haas",
        "model": "Mini Mill",
        "controller": "HAAS",
        "controller_version": "NGC 100.22",
        "kinematics": "3axis",
        "travels_mm": {"X": [-60.0, 60.0], "Y": [-45.0, 45.0], "Z": [-100.0, 30.0]},
        "spindle_curve": [[0, 1.0, 0], [1200, 4.0, 32.0], [6000, 4.0, 6.4], [10000, 2.5, 2.4]],
        "max_rpm": 10000.0,
        "min_rpm": 100.0,
        "max_feed_mm_min": 12700.0,
        "rapid_mm_min": {"X": 15000.0, "Y": 15000.0, "Z": 15000.0},
        "acceleration_mm_s2": {"X": 3000.0, "Y": 3000.0, "Z": 2500.0},
        "tool_change_seconds": 4.5,
        "index_seconds": 0.0,
        "magazine_capacity": 10,
        "coolant": ["flood"],
        "work_offsets": ["G54", "G55"],
        "hourly_rate": 34.0,
        "setup_rate": 44.0,
        "geometry_qualified": False,
    },
]


def _assembly(flute_length: float, shank_d: float, gauge: float) -> list[list[float]]:
    """Assembly silhouette above the flute: shank, taper, holder body."""
    shank_length = max(6.0, gauge * 0.28)
    taper_length = max(6.0, gauge * 0.16)
    body_length = max(1.0, gauge - flute_length - shank_length - taper_length)
    return [
        [shank_d, shank_length],
        [max(shank_d * 1.9, 20.0), taper_length],
        [44.0, body_length],
    ]


TOOLS: list[dict[str, Any]] = [
    {
        "code": "T01-FM50",
        "description": "50 mm face mill, 5 inserts, 45 degree",
        "cutter": {"type": "facemill", "diameter": 50.0, "flutes": 5, "flute_length": 6.0, "material": "carbide", "coating": "TiAlN", "number": 1, "shank_diameter": 22.0},
        "holder": {"type": "BT30 shell", "diameter": 50.0},
        "gauge_length_mm": 85.0,
        "collision_profile": _assembly(6.0, 22.0, 85.0),
        "max_rpm": 8000.0,
        "cost_per_edge": 6.4,
        "expected_life_minutes": 180.0,
        "location": "Crib A1",
    },
    {
        "code": "T02-EM16",
        "description": "16 mm 3 flute carbide endmill, square",
        "cutter": {"type": "endmill", "diameter": 16.0, "flutes": 3, "flute_length": 40.0, "corner_radius": 0.0, "material": "carbide", "coating": "TiAlN", "number": 2, "shank_diameter": 16.0},
        "holder": {"type": "BT30 hydraulic", "diameter": 44.0},
        "gauge_length_mm": 110.0,
        "collision_profile": _assembly(40.0, 16.0, 110.0),
        "max_rpm": 18000.0,
        "cost_per_edge": 26.0,
        "expected_life_minutes": 110.0,
        "location": "Crib A2",
    },
    {
        "code": "T03-EM10",
        "description": "10 mm 3 flute carbide endmill, square",
        "cutter": {"type": "endmill", "diameter": 10.0, "flutes": 3, "flute_length": 30.0, "corner_radius": 0.0, "material": "carbide", "coating": "TiAlN", "number": 3, "shank_diameter": 10.0},
        "holder": {"type": "BT30 shrink", "diameter": 44.0},
        "gauge_length_mm": 95.0,
        "collision_profile": _assembly(30.0, 10.0, 95.0),
        "max_rpm": 20000.0,
        "cost_per_edge": 18.0,
        "expected_life_minutes": 95.0,
        "location": "Crib A3",
    },
    {
        "code": "T04-EM6",
        "description": "6 mm 4 flute carbide endmill, square",
        "cutter": {"type": "endmill", "diameter": 6.0, "flutes": 4, "flute_length": 20.0, "corner_radius": 0.0, "material": "carbide", "coating": "AlTiN", "number": 4, "shank_diameter": 6.0},
        "holder": {"type": "ER20 collet", "diameter": 34.0},
        "gauge_length_mm": 80.0,
        "collision_profile": _assembly(20.0, 6.0, 80.0),
        "max_rpm": 24000.0,
        "cost_per_edge": 12.5,
        "expected_life_minutes": 70.0,
        "location": "Crib A4",
    },
    {
        "code": "T05-BN6",
        "description": "6 mm ball nose, 4 flute, for 3D finishing",
        "cutter": {"type": "endmill", "diameter": 6.0, "flutes": 4, "flute_length": 18.0, "corner_radius": 3.0, "material": "carbide", "coating": "AlTiN", "number": 5, "shank_diameter": 6.0},
        "holder": {"type": "ER20 collet", "diameter": 34.0},
        "gauge_length_mm": 78.0,
        "collision_profile": _assembly(18.0, 6.0, 78.0),
        "max_rpm": 24000.0,
        "cost_per_edge": 15.0,
        "expected_life_minutes": 60.0,
        "location": "Crib A5",
    },
    {
        "code": "T06-DR82",
        "description": "8.2 mm solid carbide drill, through coolant",
        "cutter": {"type": "drill", "diameter": 8.2, "flutes": 2, "flute_length": 50.0, "material": "carbide", "coating": "TiAlN", "number": 6, "point_angle": 140.0, "shank_diameter": 8.0},
        "holder": {"type": "ER20 collet", "diameter": 34.0},
        "gauge_length_mm": 105.0,
        "collision_profile": _assembly(50.0, 8.0, 105.0),
        "max_rpm": 12000.0,
        "cost_per_edge": 31.0,
        "expected_life_minutes": 140.0,
        "location": "Crib B1",
    },
    {
        "code": "T07-DR68",
        "description": "6.8 mm carbide drill, tapping size for M8",
        "cutter": {"type": "drill", "diameter": 6.8, "flutes": 2, "flute_length": 45.0, "material": "carbide", "coating": "TiAlN", "number": 7, "point_angle": 140.0, "shank_diameter": 8.0},
        "holder": {"type": "ER20 collet", "diameter": 34.0},
        "gauge_length_mm": 100.0,
        "collision_profile": _assembly(45.0, 8.0, 100.0),
        "max_rpm": 12000.0,
        "cost_per_edge": 28.0,
        "expected_life_minutes": 130.0,
        "location": "Crib B2",
    },
    {
        "code": "T08-CH90",
        "description": "10 mm 90 degree chamfer mill",
        "cutter": {"type": "chamfer", "diameter": 10.0, "flutes": 3, "flute_length": 8.0, "material": "carbide", "coating": "TiAlN", "number": 8, "angle_deg": 90.0, "shank_diameter": 10.0},
        "holder": {"type": "ER20 collet", "diameter": 34.0},
        "gauge_length_mm": 78.0,
        "collision_profile": _assembly(8.0, 10.0, 78.0),
        "max_rpm": 16000.0,
        "cost_per_edge": 14.0,
        "expected_life_minutes": 150.0,
        "location": "Crib B3",
    },
    {
        "code": "T09-EM20",
        "description": "20 mm 4 flute carbide endmill, high feed",
        "cutter": {"type": "endmill", "diameter": 20.0, "flutes": 4, "flute_length": 45.0, "corner_radius": 1.0, "material": "carbide", "coating": "TiAlN", "number": 9, "shank_diameter": 20.0},
        "holder": {"type": "BT30 hydraulic", "diameter": 50.0},
        "gauge_length_mm": 120.0,
        "collision_profile": _assembly(45.0, 20.0, 120.0),
        "max_rpm": 14000.0,
        "cost_per_edge": 34.0,
        "expected_life_minutes": 120.0,
        "location": "Crib B4",
    },
    {
        "code": "T10-RM12",
        "description": "12.02 mm carbide reamer, H7",
        "cutter": {"type": "reamer", "diameter": 12.02, "flutes": 6, "flute_length": 30.0, "material": "carbide", "coating": "none", "number": 10, "shank_diameter": 12.0},
        "holder": {"type": "ER20 collet", "diameter": 34.0},
        "gauge_length_mm": 95.0,
        "collision_profile": _assembly(30.0, 12.0, 95.0),
        "max_rpm": 3000.0,
        "cost_per_edge": 58.0,
        "expected_life_minutes": 200.0,
        "location": "Crib B5",
        "available": False,
    },
]

FIXTURES: list[dict[str, Any]] = [
    {
        "code": "VISE-160",
        "name": "160 mm precision vise on subplate",
        "fixture_type": "vise",
        "jaw_opening_mm": 160.0,
        "max_part_height_mm": 120.0,
        "clamp_height_mm": 8.0,
        "safe_clearance_mm": 2.0,
        "verified": True,
        "datum_scheme": {
            "primary": "Stock top face",
            "secondary": "Fixed jaw face",
            "tertiary": "Jaw end stop",
            "note": "Part sits on 20 mm parallels; grip depth 8 mm",
        },
        "solids": [
            {"name": "fixed jaw", "type": "box", "min": [-95.0, -70.0, -60.0], "max": [95.0, -32.5, -12.0], "clearance": 0.5},
            {"name": "moving jaw", "type": "box", "min": [-95.0, 32.5, -60.0], "max": [95.0, 70.0, -12.0], "clearance": 0.5},
            {"name": "vise body", "type": "box", "min": [-95.0, -70.0, -110.0], "max": [95.0, 70.0, -60.0], "clearance": 0.5},
        ],
    },
    {
        "code": "TOMBSTONE-4",
        "name": "Tombstone with four side clamps for indexed work",
        "fixture_type": "tombstone",
        "jaw_opening_mm": 200.0,
        "max_part_height_mm": 150.0,
        "clamp_height_mm": 10.0,
        "safe_clearance_mm": 3.0,
        "verified": False,
        "datum_scheme": {"primary": "Tombstone face", "secondary": "Locating pin", "tertiary": "Edge stop"},
        "solids": [
            {"name": "tombstone body", "type": "box", "min": [-120.0, -120.0, -220.0], "max": [120.0, 120.0, -30.0]},
            {"name": "side clamp -X", "type": "box", "min": [-90.0, -25.0, -30.0], "max": [-60.0, 25.0, 6.0]},
            {"name": "side clamp +X", "type": "box", "min": [60.0, -25.0, -30.0], "max": [90.0, 25.0, 6.0]},
        ],
    },
]

#: Cutting rules keyed "<cutter material>/<operation class>".
MATERIALS: list[dict[str, Any]] = [
    {
        "code": "AL6082-T6",
        "name": "Aluminium EN AW-6082 T6",
        "group": "aluminium",
        "density_g_cm3": 2.70,
        "price_per_kg": 6.80,
        "hardness_hb": 95.0,
        "kc11": 700.0,
        "mc": 0.23,
        "rules_validated": True,
        "cutting_rules": {
            "carbide/rough": {"vc_m_min": 420.0, "fz_mm": 0.085, "ap_factor": 1.0, "ae_factor": 0.40, "kc11": 700.0, "mc": 0.23, "coolant": "flood", "validated": True, "source": "AL6082-T6 carbide roughing, validated 2026-05"},
            "carbide/finish": {"vc_m_min": 520.0, "fz_mm": 0.050, "ap_factor": 0.25, "ae_factor": 0.08, "kc11": 700.0, "mc": 0.23, "coolant": "flood", "validated": True, "source": "AL6082-T6 carbide finishing, validated 2026-05"},
            "carbide/slot": {"vc_m_min": 340.0, "fz_mm": 0.050, "ap_factor": 0.5, "ae_factor": 1.0, "kc11": 700.0, "mc": 0.23, "coolant": "flood", "validated": True, "source": "AL6082-T6 full-width slotting"},
            "carbide/drill": {"vc_m_min": 120.0, "fz_mm": 0.16, "kc11": 700.0, "mc": 0.23, "coolant": "through", "validated": True, "source": "AL6082-T6 carbide drilling"},
            "carbide/ream": {"vc_m_min": 40.0, "fz_mm": 0.20, "kc11": 700.0, "mc": 0.23, "coolant": "flood", "validated": True, "source": "AL6082-T6 reaming H7"},
            "carbide/bore": {"vc_m_min": 400.0, "fz_mm": 0.040, "ap_factor": 0.3, "ae_factor": 0.3, "kc11": 700.0, "mc": 0.23, "coolant": "flood", "validated": True, "source": "AL6082-T6 helical interpolation"},
            "carbide/chamfer": {"vc_m_min": 380.0, "fz_mm": 0.045, "ap_factor": 0.2, "ae_factor": 0.3, "kc11": 700.0, "mc": 0.23, "coolant": "flood", "validated": True, "source": "AL6082-T6 chamfering"},
            "carbide/tap": {"vc_m_min": 18.0, "fz_mm": 1.25, "kc11": 700.0, "mc": 0.23, "coolant": "flood", "validated": True, "source": "AL6082-T6 synchronous tapping"},
        },
    },
    {
        "code": "S235JR",
        "name": "Structural steel S235JR",
        "group": "steel",
        "density_g_cm3": 7.85,
        "price_per_kg": 1.65,
        "hardness_hb": 120.0,
        "kc11": 1500.0,
        "mc": 0.26,
        "rules_validated": True,
        "cutting_rules": {
            "carbide/rough": {"vc_m_min": 180.0, "fz_mm": 0.090, "ap_factor": 0.8, "ae_factor": 0.35, "kc11": 1500.0, "mc": 0.26, "coolant": "flood", "validated": True, "source": "S235JR carbide roughing, validated 2026-06"},
            "carbide/finish": {"vc_m_min": 220.0, "fz_mm": 0.055, "ap_factor": 0.2, "ae_factor": 0.06, "kc11": 1500.0, "mc": 0.26, "coolant": "flood", "validated": True, "source": "S235JR carbide finishing"},
            "carbide/slot": {"vc_m_min": 140.0, "fz_mm": 0.045, "ap_factor": 0.4, "ae_factor": 1.0, "kc11": 1500.0, "mc": 0.26, "coolant": "flood", "validated": True, "source": "S235JR slotting"},
            "carbide/drill": {"vc_m_min": 80.0, "fz_mm": 0.12, "kc11": 1500.0, "mc": 0.26, "coolant": "through", "validated": True, "source": "S235JR carbide drilling"},
            "carbide/bore": {"vc_m_min": 180.0, "fz_mm": 0.040, "ap_factor": 0.25, "ae_factor": 0.25, "kc11": 1500.0, "mc": 0.26, "coolant": "flood", "validated": True, "source": "S235JR interpolation"},
            "carbide/chamfer": {"vc_m_min": 160.0, "fz_mm": 0.035, "ap_factor": 0.2, "ae_factor": 0.3, "kc11": 1500.0, "mc": 0.26, "coolant": "flood", "validated": True, "source": "S235JR chamfering"},
            "carbide/ream": {"vc_m_min": 25.0, "fz_mm": 0.15, "kc11": 1500.0, "mc": 0.26, "coolant": "flood", "validated": True, "source": "S235JR reaming"},
        },
    },
    {
        "code": "SS316L",
        "name": "Stainless steel 316L",
        "group": "stainless",
        "density_g_cm3": 8.00,
        "price_per_kg": 6.20,
        "hardness_hb": 170.0,
        "kc11": 2000.0,
        "mc": 0.25,
        "rules_validated": False,
        "notes": "Rules entered by applications engineering; pending validation on the pilot machines.",
        "cutting_rules": {
            "carbide/rough": {"vc_m_min": 110.0, "fz_mm": 0.070, "ap_factor": 0.6, "ae_factor": 0.25, "kc11": 2000.0, "mc": 0.25, "coolant": "flood", "validated": False, "source": "316L starting values, NOT validated"},
            "carbide/finish": {"vc_m_min": 140.0, "fz_mm": 0.045, "ap_factor": 0.15, "ae_factor": 0.05, "kc11": 2000.0, "mc": 0.25, "coolant": "flood", "validated": False, "source": "316L starting values, NOT validated"},
            "carbide/drill": {"vc_m_min": 45.0, "fz_mm": 0.08, "kc11": 2000.0, "mc": 0.25, "coolant": "through", "validated": False, "source": "316L starting values, NOT validated"},
        },
    },
]

POSTS: list[dict[str, Any]] = [
    {
        "code": "FANUC-VMC01",
        "name": "FANUC 31i-B5 for Robodrill cell 1",
        "dialect": "fanuc",
        "machine_code": "VMC-01",
        "machine_model": "Robodrill alpha-D21MiB5",
        "controller": "FANUC",
        "controller_version": "31i-B5",
        "definition": {
            "line_numbers": {"enabled": True, "start": 10, "increment": 10, "prefix": "N"},
            "canned_cycles": {"G81": True, "G82": True, "G83": True, "G84": True, "G85": True},
            "decimals": {"xyz": 3, "feed": 1, "rpm": 0, "ijk": 3},
            "max_line_length": 72,
            "sequence_stop_between_setups": True,
        },
    },
    {
        "code": "FANUC-VMC02",
        "name": "FANUC 31i-B5 for Trunnion cell 2, indexed 3+2",
        "dialect": "fanuc",
        "machine_code": "VMC-02",
        "machine_model": "SPEEDIO M200X3",
        "controller": "FANUC",
        "controller_version": "31i-B5",
        "definition": {
            "line_numbers": {"enabled": True, "start": 10, "increment": 10, "prefix": "N"},
            "canned_cycles": {"G81": True, "G82": True, "G83": True, "G84": True, "G85": True},
            "decimals": {"xyz": 3, "feed": 1, "rpm": 0, "ijk": 3},
            "max_line_length": 72,
            "sequence_stop_between_setups": True,
        },
    },
]
